FROM alpine:latest
RUN apk add --no-cache \
    bash \
    python3 \
    partclone \
    xorriso \
    e2fsprogs \
    e2fsprogs-extra \
    pigz \
    coreutils \
    tar \
    rsync \
    util-linux \
    findmnt \
    ffmpeg
